## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [25]:
import numpy as np
import pandas as pd
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [26]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [27]:
from sklearn.model_selection import train_test_split
one_index=np.where(y==1)[0]
zero_index=np.where(y==0)[0]

In [38]:
X_one_train, X_one_test, y_one_train, y_one_test = train_test_split(X[one_index], y[one_index], test_size=10)
X_zero_train, X_zero_test, y_zero_train, y_zero_test = train_test_split(X[zero_index], y[zero_index], test_size=10)
X_one_test

array([[130, 131, 132, 133, 134],
       [ 60,  61,  62,  63,  64],
       [ 80,  81,  82,  83,  84],
       [180, 181, 182, 183, 184],
       [ 35,  36,  37,  38,  39],
       [175, 176, 177, 178, 179],
       [155, 156, 157, 158, 159],
       [185, 186, 187, 188, 189],
       [170, 171, 172, 173, 174],
       [165, 166, 167, 168, 169]])

In [41]:
#np.concatenate((X_one_train, X_zero_train), axis=None)

x_train=np.concatenate((X_one_train, X_zero_train), axis=None)
y_test=np.concatenate((y_one_test, y_zero_test), axis=None)

In [45]:
y_test

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])